-- ============================================================
-- FLAPVERSE ONLINE PLAYER SYSTEM
-- Account model: Guest Username ID + Password OR optional private Email ID + Password
-- Run this ONCE in Supabase -> SQL Editor -> New query -> Run
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.fv_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now(),
  constraint fv_username_format check (username ~ '^[a-z0-9_]{3,20}$')
);

create table if not exists public.fv_player_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  total_pipes bigint not null default 0,
  deaths bigint not null default 0,
  coins_earned bigint not null default 0,
  favorite_world text,
  best_score integer not null default 0,
  achievement_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.fv_friends (
  id uuid primary key default gen_random_uuid(),
  requester uuid not null references auth.users(id) on delete cascade,
  addressee uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  constraint fv_no_self_friend check (requester <> addressee),
  constraint fv_friend_pair_unique unique (requester,addressee)
);

create table if not exists public.fv_challenges (
  id uuid primary key default gen_random_uuid(),
  sender uuid not null references auth.users(id) on delete cascade,
  receiver uuid not null references auth.users(id) on delete cascade,
  target_score integer not null default 1,
  status text not null default 'pending' check (status in ('pending','accepted','completed','declined')),
  sender_score integer not null default 0,
  receiver_score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.fv_hall_of_fame (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_name text not null,
  winner_user_id uuid references auth.users(id) on delete set null,
  winner_username text not null,
  winning_score integer not null,
  badge text not null default '🏆',
  won_at timestamptz not null default now()
);

alter table public.fv_profiles enable row level security;
alter table public.fv_player_state enable row level security;
alter table public.fv_friends enable row level security;
alter table public.fv_challenges enable row level security;
alter table public.fv_hall_of_fame enable row level security;

drop policy if exists "profiles_read_authenticated" on public.fv_profiles;
create policy "profiles_read_authenticated" on public.fv_profiles
for select to authenticated using (true);

drop policy if exists "profiles_insert_self" on public.fv_profiles;
create policy "profiles_insert_self" on public.fv_profiles
for insert to authenticated with check (id = auth.uid());

drop policy if exists "profiles_update_self" on public.fv_profiles;
create policy "profiles_update_self" on public.fv_profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "state_read_authenticated" on public.fv_player_state;
create policy "state_read_authenticated" on public.fv_player_state
for select to authenticated using (true);

drop policy if exists "state_insert_self" on public.fv_player_state;
create policy "state_insert_self" on public.fv_player_state
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "state_update_self" on public.fv_player_state;
create policy "state_update_self" on public.fv_player_state
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "friends_read_involved" on public.fv_friends;
create policy "friends_read_involved" on public.fv_friends
for select to authenticated using (requester = auth.uid() or addressee = auth.uid());

drop policy if exists "friends_insert_requester" on public.fv_friends;
create policy "friends_insert_requester" on public.fv_friends
for insert to authenticated with check (requester = auth.uid());

drop policy if exists "friends_update_involved" on public.fv_friends;
create policy "friends_update_involved" on public.fv_friends
for update to authenticated using (requester = auth.uid() or addressee = auth.uid())
with check (requester = auth.uid() or addressee = auth.uid());

drop policy if exists "friends_delete_involved" on public.fv_friends;
create policy "friends_delete_involved" on public.fv_friends
for delete to authenticated using (requester = auth.uid() or addressee = auth.uid());

drop policy if exists "challenges_read_involved" on public.fv_challenges;
create policy "challenges_read_involved" on public.fv_challenges
for select to authenticated using (sender = auth.uid() or receiver = auth.uid());

drop policy if exists "challenges_insert_sender" on public.fv_challenges;
create policy "challenges_insert_sender" on public.fv_challenges
for insert to authenticated with check (sender = auth.uid());

drop policy if exists "challenges_update_involved" on public.fv_challenges;
create policy "challenges_update_involved" on public.fv_challenges
for update to authenticated using (sender = auth.uid() or receiver = auth.uid())
with check (sender = auth.uid() or receiver = auth.uid());

drop policy if exists "hof_public_read" on public.fv_hall_of_fame;
create policy "hof_public_read" on public.fv_hall_of_fame
for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on public.fv_hall_of_fame to anon, authenticated;
grant select, insert, update on public.fv_profiles to authenticated;
grant select, insert, update on public.fv_player_state to authenticated;
grant select, insert, update, delete on public.fv_friends to authenticated;
grant select, insert, update on public.fv_challenges to authenticated;

-- Secure Hall-of-Fame claim for the current 7-day Golden Pass event.
create or replace function public.fv_claim_golden_pass_event()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  w record;
begin
  if auth.uid() is null then
    return jsonb_build_object('won',false,'reason','login_required');
  end if;

  if now() < timestamptz '2026-09-02 00:00:00+05:30' then
    return jsonb_build_object('won',false,'reason','event_not_ended');
  end if;

  select player_id, username, best_score
  into w
  from public.flapverse_leaderboard
  order by best_score desc, updated_at asc
  limit 1;

  if w.player_id is null or coalesce(w.best_score,0) <= 990 then
    return jsonb_build_object('won',false,'reason','no_qualifying_winner');
  end if;

  if w.player_id <> auth.uid()::text then
    return jsonb_build_object('won',false,'reason','not_winner');
  end if;

  insert into public.fv_hall_of_fame
    (event_key,event_name,winner_user_id,winner_username,winning_score,badge,won_at)
  values
    ('golden-pass-aug-2026','7-DAY GOLDEN PASS CHALLENGE',auth.uid(),w.username,w.best_score,'👑',now())
  on conflict (event_key) do nothing;

  return jsonb_build_object('won',true,'username',w.username,'score',w.best_score);
end;
$$;

grant execute on function public.fv_claim_golden_pass_event() to authenticated;
